name: 'Build and deploy'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4

      - name: npm install
        run: npm i

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Generate docs
        run: npm run typedoc

      - name: Deploy
        run: echo todo
